# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import kvstore_pb2 as proto_dot_kvstore__pb2


class KeyValueStoreStub(object):
    """*
    Service chính để client tương tác với hệ thống
    Cung cấp các thao tác cơ bản: PUT, GET, DELETE
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/kvstore.KeyValueStore/Put',
                request_serializer=proto_dot_kvstore__pb2.PutRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.PutResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/kvstore.KeyValueStore/Get',
                request_serializer=proto_dot_kvstore__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.GetResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/kvstore.KeyValueStore/Delete',
                request_serializer=proto_dot_kvstore__pb2.DeleteRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.DeleteResponse.FromString,
                )
        self.ListKeys = channel.unary_unary(
                '/kvstore.KeyValueStore/ListKeys',
                request_serializer=proto_dot_kvstore__pb2.ListKeysRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.ListKeysResponse.FromString,
                )


class KeyValueStoreServicer(object):
    """*
    Service chính để client tương tác với hệ thống
    Cung cấp các thao tác cơ bản: PUT, GET, DELETE
    """

    def Put(self, request, context):
        """Lưu một cặp key-value vào hệ thống
        Client gửi request đến bất kỳ node nào
        Node sẽ xác định node đúng thông qua consistent hashing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Lấy value theo key
        Có thể đọc từ primary hoặc replica
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Xóa một key khỏi hệ thống
        Xóa cả trên primary và replicas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKeys(self, request, context):
        """Lấy danh sách tất cả keys (để debug/testing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=proto_dot_kvstore__pb2.PutRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=proto_dot_kvstore__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=proto_dot_kvstore__pb2.DeleteRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.DeleteResponse.SerializeToString,
            ),
            'ListKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKeys,
                    request_deserializer=proto_dot_kvstore__pb2.ListKeysRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.ListKeysResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """*
    Service chính để client tương tác với hệ thống
    Cung cấp các thao tác cơ bản: PUT, GET, DELETE
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KeyValueStore/Put',
            proto_dot_kvstore__pb2.PutRequest.SerializeToString,
            proto_dot_kvstore__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KeyValueStore/Get',
            proto_dot_kvstore__pb2.GetRequest.SerializeToString,
            proto_dot_kvstore__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KeyValueStore/Delete',
            proto_dot_kvstore__pb2.DeleteRequest.SerializeToString,
            proto_dot_kvstore__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KeyValueStore/ListKeys',
            proto_dot_kvstore__pb2.ListKeysRequest.SerializeToString,
            proto_dot_kvstore__pb2.ListKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class NodeServiceStub(object):
    """*
    Service cho giao tiếp giữa các nodes
    Xử lý replication, failure detection, recovery
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/kvstore.NodeService/Heartbeat',
                request_serializer=proto_dot_kvstore__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.HeartbeatResponse.FromString,
                )
        self.ForwardPut = channel.unary_unary(
                '/kvstore.NodeService/ForwardPut',
                request_serializer=proto_dot_kvstore__pb2.ForwardPutRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.ForwardPutResponse.FromString,
                )
        self.ForwardGet = channel.unary_unary(
                '/kvstore.NodeService/ForwardGet',
                request_serializer=proto_dot_kvstore__pb2.ForwardGetRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.ForwardGetResponse.FromString,
                )
        self.ForwardDelete = channel.unary_unary(
                '/kvstore.NodeService/ForwardDelete',
                request_serializer=proto_dot_kvstore__pb2.ForwardDeleteRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.ForwardDeleteResponse.FromString,
                )
        self.Replicate = channel.unary_unary(
                '/kvstore.NodeService/Replicate',
                request_serializer=proto_dot_kvstore__pb2.ReplicateRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.ReplicateResponse.FromString,
                )
        self.GetSnapshot = channel.unary_unary(
                '/kvstore.NodeService/GetSnapshot',
                request_serializer=proto_dot_kvstore__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.SnapshotResponse.FromString,
                )
        self.JoinCluster = channel.unary_unary(
                '/kvstore.NodeService/JoinCluster',
                request_serializer=proto_dot_kvstore__pb2.JoinRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.JoinResponse.FromString,
                )
        self.GetMembership = channel.unary_unary(
                '/kvstore.NodeService/GetMembership',
                request_serializer=proto_dot_kvstore__pb2.MembershipRequest.SerializeToString,
                response_deserializer=proto_dot_kvstore__pb2.MembershipResponse.FromString,
                )


class NodeServiceServicer(object):
    """*
    Service cho giao tiếp giữa các nodes
    Xử lý replication, failure detection, recovery
    """

    def Heartbeat(self, request, context):
        """Gửi heartbeat để báo node còn sống
        Mỗi node gửi heartbeat đến tất cả nodes khác định kỳ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardPut(self, request, context):
        """Forward request từ node này sang node khác
        Dùng khi client connect đến node không chứa data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replicate(self, request, context):
        """Replicate data từ primary node sang replica
        Đảm bảo mỗi key có ít nhất 2 copies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Lấy snapshot toàn bộ data từ node khác
        Dùng khi node restart và cần khôi phục dữ liệu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinCluster(self, request, context):
        """Thông báo node mới join vào cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMembership(self, request, context):
        """Lấy thông tin về membership (danh sách nodes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_kvstore__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ForwardPut': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardPut,
                    request_deserializer=proto_dot_kvstore__pb2.ForwardPutRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.ForwardPutResponse.SerializeToString,
            ),
            'ForwardGet': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardGet,
                    request_deserializer=proto_dot_kvstore__pb2.ForwardGetRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.ForwardGetResponse.SerializeToString,
            ),
            'ForwardDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardDelete,
                    request_deserializer=proto_dot_kvstore__pb2.ForwardDeleteRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.ForwardDeleteResponse.SerializeToString,
            ),
            'Replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=proto_dot_kvstore__pb2.ReplicateRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.ReplicateResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=proto_dot_kvstore__pb2.SnapshotRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.SnapshotResponse.SerializeToString,
            ),
            'JoinCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinCluster,
                    request_deserializer=proto_dot_kvstore__pb2.JoinRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.JoinResponse.SerializeToString,
            ),
            'GetMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMembership,
                    request_deserializer=proto_dot_kvstore__pb2.MembershipRequest.FromString,
                    response_serializer=proto_dot_kvstore__pb2.MembershipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """*
    Service cho giao tiếp giữa các nodes
    Xử lý replication, failure detection, recovery
    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.NodeService/Heartbeat',
            proto_dot_kvstore__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_kvstore__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ForwardPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.NodeService/ForwardPut',
            proto_dot_kvstore__pb2.ForwardPutRequest.SerializeToString,
            proto_dot_kvstore__pb2.ForwardPutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ForwardGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.NodeService/ForwardGet',
            proto_dot_kvstore__pb2.ForwardGetRequest.SerializeToString,
            proto_dot_kvstore__pb2.ForwardGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ForwardDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.NodeService/ForwardDelete',
            proto_dot_kvstore__pb2.ForwardDeleteRequest.SerializeToString,
            proto_dot_kvstore__pb2.ForwardDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.NodeService/Replicate',
            proto_dot_kvstore__pb2.ReplicateRequest.SerializeToString,
            proto_dot_kvstore__pb2.ReplicateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.NodeService/GetSnapshot',
            proto_dot_kvstore__pb2.SnapshotRequest.SerializeToString,
            proto_dot_kvstore__pb2.SnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.NodeService/JoinCluster',
            proto_dot_kvstore__pb2.JoinRequest.SerializeToString,
            proto_dot_kvstore__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.NodeService/GetMembership',
            proto_dot_kvstore__pb2.MembershipRequest.SerializeToString,
            proto_dot_kvstore__pb2.MembershipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
